<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        // Guzzle HTTP client options — used to route Bot API requests
        // through a local proxy when api.telegram.org is unreachable.
        // Set TELEGRAM_PROXY=socks5://127.0.0.1:10808 in .env (e.g. v2rayN).
        // verify=false: local dev behind a MITM proxy (v2rayN/AV) injects its own cert.
        'client' => env('TELEGRAM_PROXY')
            ? [
                'proxy'  => ['https' => env('TELEGRAM_PROXY'), 'http' => env('TELEGRAM_PROXY')],
                'verify' => (bool) env('TELEGRAM_VERIFY_SSL', false),
                'curl'   => [
                    CURLOPT_SSL_VERIFYPEER => (bool) env('TELEGRAM_VERIFY_SSL', false),
                    CURLOPT_SSL_VERIFYHOST => (bool) env('TELEGRAM_VERIFY_SSL', false) ? 2 : 0,
                ],
            ]
            : [],
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),

    // Secret token used in the webhook URL path: /tg/webhook/{secret}.
    // Prevents randoms from hitting the endpoint. Set in .env.
    'webhook_secret' => env('TELEGRAM_WEBHOOK_SECRET'),
];
